export const projectsData = [
  {
    id: "moness-table-reservation",
    photo: "moness-table-reservation.png",
    title: "Moness Table Reservation (1/3)",
    liveSiteLink: "https://172v-moness-table-reservation.netlify.app/",
    liveSite2Link: null,
    liveSiteLabel: "Front-End",
    liveSite2Label: null,
    gitFrontLink:
      "https://github.com/paul172v/moness-table-reservation--customer--frontend",
    gitFront2Link: null,
    gitFrontLabel: "Github Front-End",
    gitFront2Label: null,
    gitBack: "https://github.com/paul172v/moness-backend",
    keyFeatures: [
      "React/TypeScript",
      "Node/Express/MongoDB",
      "Full-Stack",
      "Booking Logic",
      "Responsive Design",
    ],
    description:
      "This web app is a prototype customer-side table reservation system for the Moness Resort, a real business. The app will only allow 15 people to be booked per every 15 minuet time slot. It will also only allow users to book a table within the restaurant's opening hours.",
    descriptionSize: "normal",
  },

  {
    id: "moness-flemmyng-menu",
    photo: "moness-flemmyng-menu.png",
    title: "Moness Flemmyng Menu (2/3)",
    liveSiteLink: "https://172v-moness-menu.netlify.app/",
    liveSite2Link: null,
    liveSiteLabel: "Front-End",
    liveSite2Label: null,
    gitFrontLink: "https://github.com/paul172v/moness-flemmyng-menu",
    gitFront2Link: null,
    gitFrontLabel: "Github Front-End",
    gitFront2Label: null,
    gitBack: "https://github.com/paul172v/moness-backend",
    keyFeatures: [
      "React/TypeScript",
      "Node/Express/MongoDB",
      "Full-Stack",
      "Dynamic Rendering",
      "Responsive Design",
    ],
    description:
      "This web app is a prototype customer-side online menu for the Moness Resort, a real business. The app will take a list of menu items for each menu category (taken from a MongoDB database) and dynamically generate the menu. The design is intended to mimic the paper menu and it will collapse into a single column for tablets and mobiles for easier reading.",
    descriptionSize: "normal",
  },

  {
    id: "moness-staff-portal",
    photo: "moness-staff-portal.png",
    title: "Moness Staff Portal (3/3)",
    liveSiteLink: "https://172v-moness-staff-portal.netlify.app/",
    liveSite2Link: null,
    liveSiteLabel: "Front-End",
    liveSite2Label: null,
    gitFrontLink: "https://github.com/paul172v/moness-staff-portal--frontend",
    gitFront2Link: null,
    gitFrontLabel: "Github Front-End",
    gitFront2Label: null,
    gitBack: "https://github.com/paul172v/moness-backend",
    keyFeatures: [
      "React/TypeScript",
      "Node/Express/MongoDB",
      "Full-Stack",
      "User Authentication",
      "User Interface",
      "Responsive Design",
    ],
    description:
      "This web app is a prototype staff-side user interface that allows staff to view and alter bookings from the table reservation app, block time slots for table bookings, and view and alter the menu items on the Flemmyng menu. It has user authentication, and all users have an access level that is set by managers. To log in you can use the account 'manger@moness.com' and the password 'password'.",
    descriptionSize: "normal",
  },

  {
    id: "moness-map",
    photo: "moness-map.png",
    title: "Moness Online Map",
    liveSiteLink: "https://172v-moness-map.netlify.app/",
    liveSite2Link: null,
    liveSiteLabel: "Front-End",
    liveSite2Label: null,
    gitFrontLink: "hhttps://github.com/paul172v/moness-map",
    gitFront2Link: null,
    gitFrontLabel: "Github Front-End",
    gitFront2Label: null,
    gitBack: null,
    keyFeatures: [
      "React/TypeScript",
      "Leaflet",
      "Full-Stack",
      "Searchable Cottages",
    ],
    description:
      "This web app is a customer-side online map of the Moness resort showing the location of the hotel reception and various facilities but it's primary function is to allow guests to find their cottage easily on the resort grounds. This app was made using React/TypeScript and the Leaflet.js Library. It is currently being used by the hotel housekeeping staff for the same purpose as it has proved more convenient than the paper maps they were using previously.",
    descriptionSize: "normal",
  },

  {
    id: "customGPT",
    photo: "customGPT.png",
    title: "Moness Blog CustomGPT",
    liveSiteLink:
      "https://chatgpt.com/g/g-686ec718f7408191b0ebbad3081b5aaf-moness-blog-assistant",
    liveSite2Link: "https://www.facebook.com/monessresort",
    liveSiteLabel: "CustomGPT",
    liveSite2Label: "Moness Facebook Page",
    gitFrontLink: null,
    gitFront2Link: null,
    gitFrontLabel: null,
    gitFront2Label: null,
    gitBack: null,
    keyFeatures: ["CustomGPT prompting"],
    description:
      "This CustomGPT chatbot mimics the writing style and format of the Moness Facebook blog posts, allowing staff to quickly and easily generate content for the blog even without a copywriting skill-set. It takes minimal information from staff such as subject, event dates, entry fees and other criteria including links and incorporates them into a professional and authentic sounding blog post in the style and format of previous blog posts made by Moness staff.",
    descriptionSize: "normal",
  },
  {
    id: "mandarin-app",
    photo: "mandarin-app.png",
    title: "Mandarin Study App",
    liveSiteLink: "https://172v-mandarin-flashcard-app.netlify.app/",
    liveSite2Link: null,
    liveSiteLabel: "Front-End",
    liveSite2Label: null,
    gitFrontLink: "https://github.com/paul172v/172v-mandarin-flashcard-app",
    gitFront2Link: null,
    gitFrontLabel: null,
    gitFront2Label: null,
    gitBack: null,
    keyFeatures: ["React/TypeScript", "Bootstrap", "Responsive Design"],
    description:
      "I've been studying mandarin using the audiobook 'Learn Mandarin Chinese with Paul Noble for Beginners - Complete Course', I made this flashcard app to help me study the hanzi & pinyin components since the audiobook only teaches the spoken language. It is the first app I have ever created to help myself with a real-world problem and it's been super helpful.",
    descriptionSize: "normal",
  },
];

export default projectsData;
